import { useEffect } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useGetUserQuery } from '@/features/auth/authApi'
import { useRouter } from 'next/router'
import { useDispatch, useSelector } from 'react-redux'
import { addProduct } from '@/features/auth/authSlice'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const { data, isLoading, error, isError, refetch, } = useGetUserQuery()
  console.log(data)
  const router = useRouter()
  const { product } = useSelector(state => state || {})
  const dispatch = useDispatch()
  console.log(product)
  useEffect(() => {
    if (data) {
      dispatch(addProduct(data))
    }
  }, [data, dispatch])

  if (isLoading) return <div style={{
    textAlign: 'center',
    margin: "20px"
  }}>Loading</div>


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div>
          {
            data && data?.map(({ email, name, id }, i) => <div
              key={i}
              style={{
                textAlign: "center",
                padding: "30px 20px"
              }}
            >
              <p>{name}</p>
              <p>{email}</p>
              <p>{id}</p>
              <button onClick={() => router.push(`/${id}`)}>Get User Details</button>
            </div>)
          }
        </div>
      </main>
    </>
  )
}
